### ISSUE TITLE
Language Specific Code

### ISSUE THREAD

**Issue by jschpp** [rhymeswithmogul/SecurityTxtToolkit#3]
Since you are using `Select-String` to look for the english message parts in the `gpg` output the gpg check will fail on a non english os.

It's more or less understood that the output of `gpg --verify` shouldn't be parsed like that. See this thread: https://lists.gnupg.org/pipermail/gnupg-users/2005-July/026212.html

Instead you should use `gpg --status-fd 1 --verify` which will add machine readable output.
```plain
[GNUPG:] NEWSIG
gpg: Signatur vom 12.05.2023 10:20:19 Mitteleurop�ische Sommerzeit
gpg:                mittels EDDSA-Schlüssel 50E6EA9B7AFD2553457C77C8A7F4B35E85BB2BAA
[GNUPG:] KEY_CONSIDERED 50E6EA9B7AFD2553457C77C8A7F4B35E85BB2BAA 0
[GNUPG:] SIG_ID J9x1yaxahXcGXBiOAfw+N7a0VxI 2023-05-12 1683879619
[GNUPG:] KEY_CONSIDERED 50E6EA9B7AFD2553457C77C8A7F4B35E85BB2BAA 0
[GNUPG:] GOODSIG A7F4B35E85BB2BAA IT Sicherheit Johann Wolfgang Goethe-Universit├ñt Frankfurt <it-sicherheit@uni-frankfurt.de>
gpg: Korrekte Signatur von "IT Sicherheit Johann Wolfgang Goethe-Universität Frankfurt <it-sicherheit@uni-frankfurt.de>" [ultimativ]
[GNUPG:] VALIDSIG 50E6EA9B7AFD2553457C77C8A7F4B35E85BB2BAA 2023-05-12 1683879619 0 4 0 22 10 01 50E6EA9B7AFD2553457C77C8A7F4B35E85BB2BAA
[GNUPG:] TRUST_ULTIMATE 0 pgp
```
See all parts starting with `[GNUPG]`

I'd be open to write a PR if you're interested.

Thank you for this nifty tool nevertheless :)

**Comment by rhymeswithmogul** [comment]
I didn't know that. Thank you!

If you'd like to submit a PR, go for it. I’ll review it and merge it when I can.

**Comment by rhymeswithmogul** [comment]
Thank you again!
